FROM caddy:2-builder@sha256:198d47eaee306d4d0c38a9960c89ff2c959aa29ad51d3e2dafa3e93ac961782a AS builder
RUN xcaddy build v2.11.4 \
    --with github.com/mholt/caddy-l4@v0.1.2 \
    --replace golang.org/x/text=golang.org/x/text@v0.39.0 \
    --replace google.golang.org/grpc=google.golang.org/grpc@v1.82.1

FROM caddy:2@sha256:844f60b64e4724a5aa8245e019dace0d3f199f7433ce6c57676cb30a920dbad9
RUN apk add --no-cache --upgrade c-ares curl libcurl \
    && addgroup -S -g 10003 noctweave-caddy \
    && adduser -S -D -u 10003 -G noctweave-caddy -h /home/noctweave-caddy noctweave-caddy \
    && mkdir -p /config /data \
    && chown -R noctweave-caddy:noctweave-caddy /config /data
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
USER noctweave-caddy:noctweave-caddy
